### ISSUE TITLE
Weekly Scrum March 13th - March 26th

### ISSUE THREAD

**Issue by mrunal-patel1997** [RhysMelanson/SYSC_4806_Survey_Monkey#18]

**Comment by andrewehatt** [comment]
What I did this week:

- Worked on addition functionality to answer questions
- added template in resources

What I had trouble with:

- had trouble with the controllers and templates

**Comment by NRA3110** [comment]
What I did this week:

- Added basic username login functionality
- Added login template in resources 

What I had trouble with:

- had difficulty with user controller

**Comment by HassanAYusuf** [comment]
What I did this Sprint:

- Fixed milestone 1 to better fit our project
- Created a model of the answer class and connect it to the question class using a one to many relationship
- Updated the question model to cover all three types of questions
- created views to create all types of questions
- helped colleagues to complete their tasks
- Reviewed pull requests and reverted them when the master branch crashed

What I will do next Sprint:

- Implement web page traversal so that it is logical
- Connect question to survey so that the added question is for the specific survey 
- Create a list of all the question in the survey

What is holding me back:

- had difficulty implementing a single page application
- had difficulty separating the question types from question model thus making the model to have many columns

**Comment by RhysMelanson** [comment]
What I did this Sprint:

- Created a list of all the surveys currently available
- Made it possible to select a survey and view the answers

What I will do next Sprint 

- Implement the user factor so that only the survey creator can view the answers
- Implement graphical output for the numerical and multiple choice questions

What is holding me back:

- Had trouble sending over the ID of the specific survey from front end to back end

**Comment by mrunal-patel1997** [comment]
What I did this week:

- Created a page to handle creating new Surveys.

- Added Functionalities to handle error pages.

What I will do next Sprint

- Implement User view of the surveys
- Locking the survey by a user

What is holding me back:

- Difficulty with controller and HTML page creation.
